# Generated by Django 2.2.2 on 2019-06-27 12:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190627_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to=app.models.get_file_path),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('file', ''), ('text', '')), _negated=True), name='text_or_file_must_filled'),
        ),
    ]
